# Generated by Django 5.2.12 on 2026-04-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_orderdetails_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='stripe_payment_intent',
            field=models.CharField(max_length=200),
        ),
    ]
